const forExec = document.getElementById("for-exec")
const forInit = document.getElementById("for-init")
const forCond = document.getElementById("for-cond")
const forIter = document.getElementById("for-iter")
const forBody = document.getElementById("for-body")